#This file is a template used in creating the GUI for editing the experiment configuration. It documents all hardware and software that the program knows about. When new pieces of hardware (or configurable software) are added with new interfaces, they should be added here, together with their configuration information, if any.

#The GUI uses the "fields" dictionary to generate the configuration interface. Each field must be specified as a type. Known types are: role, path, str, int, magnitude, float, bool, and ok_fpga

#In addition to the specified fields, there is also an "enabled" field which is common to all items, so it does not need to be listed here. It will, however, appear in the resulting ExptConfig.yml file

#"software" is a dictionary of particular pieces of functionality available in the software, which have their own configuration information. For example, "Voltages" is a software feature, which must be configured by specifying its corresponding hardware. Hardware is a field of type "role," which means that the hardware can be set to any piece of hardware whose 'roles' field contains 'Voltages'.
software:
  &P Pulser:
    description: The main pulser interface used for running experiments
    fields:
      hardware: role
  &V Voltages:
    description: Interface for controlling a set of voltages
    fields:
      hardware: role
  Timestamps:
    description: Interface for reading and plotting the timestamps of TTL pulses
  Memory Profiler:
    description: Interface for memory profiling and object counting
  Timeseries Database:
    description: Use Influx timeseries database
    fields:
      host: str
      database: str

#"hardware" are pieces of hardware together with configuration information. If a hardware has a role, it can be selected under the corresponding software's "hardware" field.
hardware:
  "Opal Kelly FPGA":
    description: FPGA module from Opal Kelly
    roles:
      - *P
      - *V
    fields:
      device: ok_fpga
      bitFile: path
      uploadOnStartup: bool
  "Auxiliary Pulser":
    description: Auxiliary pulser
    fields:
        device: ok_fpga
        bitFile: path
        uploadOnStartup: bool
        DAC: bool
        DDS: bool
        PulserParameters: bool
        Shutters: bool
  NI DAC Chassis:
    description: DAC system from National Instruments used to output voltages
    roles:
      - *V
    fields:
      configFile: path
  Chase DA12000 AWG:
    description: Arbitrary Waveform Generator DA12000 from Chase Scientific Company
    fields:
      sampleRate: magnitude
      DLL: path
      cardNumber: int
  Lecroy 1102 AWG:
    description: Two channel Arbitrary Waveform Generator 1102 from Lecroy
    fields:
      ipAddress: str
      port: int
      sampleRate: magnitude
      extClockFrequency: magnitude
  Dummy AWG:
    description: AWG interface that doesn't do anything (i.e. without any corresponding hardware)
    fields:
      sampleRate: magnitude
  Conex Motion:
    description: Conex motorized actuators from Newport Corporation
  APT Motion:
    description: APT motorized actuators from Thorlabs
    fields:
        dllPath: path
  Lab Brick:
    description: Vaunix Lab Brick synthesizer
    fields:
        dllPath: path
  VISA:
    description: communication with peripherals (e.g. GPIB, RS232, USB, Ethernet)
  HighFinesse Wavemeter:
    description: HighFinesse Wavemeter from Toptica photonics for reading laser wavelengths, with Java applet web interface
    fields:
        uri: str